version: '2'
services:
    metrics-app:
        image: metrics
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://metrics-postgresql:5432/metrics
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    metrics-postgresql:
        extends:
            file: postgresql.yml
            service: metrics-postgresql
