//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.21 at 11:21:27 PM SAMT 
//


package ru.cedra.metrics.domain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CurrencyEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CurrencyEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="YND_FIXED"/>
 *     &lt;enumeration value="RUB"/>
 *     &lt;enumeration value="CHF"/>
 *     &lt;enumeration value="EUR"/>
 *     &lt;enumeration value="KZT"/>
 *     &lt;enumeration value="TRY"/>
 *     &lt;enumeration value="UAH"/>
 *     &lt;enumeration value="USD"/>
 *     &lt;enumeration value="BYN"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CurrencyEnum")
@XmlEnum
public enum CurrencyEnum {

    YND_FIXED,
    RUB,
    CHF,
    EUR,
    KZT,
    TRY,
    UAH,
    USD,
    BYN;

    public String value() {
        return name();
    }

    public static CurrencyEnum fromValue(String v) {
        return valueOf(v);
    }

}
