//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.21 at 11:21:27 PM SAMT 
//


package ru.cedra.metrics.domain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FieldEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FieldEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AdFormat"/>
 *     &lt;enumeration value="AdGroupId"/>
 *     &lt;enumeration value="AdGroupName"/>
 *     &lt;enumeration value="AdId"/>
 *     &lt;enumeration value="AdNetworkType"/>
 *     &lt;enumeration value="Age"/>
 *     &lt;enumeration value="AudienceTargetId"/>
 *     &lt;enumeration value="AvgClickPosition"/>
 *     &lt;enumeration value="AvgCpc"/>
 *     &lt;enumeration value="AvgImpressionPosition"/>
 *     &lt;enumeration value="AvgPageviews"/>
 *     &lt;enumeration value="BounceRate"/>
 *     &lt;enumeration value="Bounces"/>
 *     &lt;enumeration value="CampaignId"/>
 *     &lt;enumeration value="CampaignName"/>
 *     &lt;enumeration value="CampaignType"/>
 *     &lt;enumeration value="CarrierType"/>
 *     &lt;enumeration value="ClickType"/>
 *     &lt;enumeration value="Clicks"/>
 *     &lt;enumeration value="ConversionRate"/>
 *     &lt;enumeration value="Conversions"/>
 *     &lt;enumeration value="Cost"/>
 *     &lt;enumeration value="CostPerConversion"/>
 *     &lt;enumeration value="Criteria"/>
 *     &lt;enumeration value="CriteriaId"/>
 *     &lt;enumeration value="CriteriaType"/>
 *     &lt;enumeration value="Ctr"/>
 *     &lt;enumeration value="Date"/>
 *     &lt;enumeration value="Device"/>
 *     &lt;enumeration value="DynamicTextAdTargetId"/>
 *     &lt;enumeration value="ExternalNetworkName"/>
 *     &lt;enumeration value="Gender"/>
 *     &lt;enumeration value="GoalsRoi"/>
 *     &lt;enumeration value="ImpressionShare"/>
 *     &lt;enumeration value="Impressions"/>
 *     &lt;enumeration value="Keyword"/>
 *     &lt;enumeration value="LocationOfPresenceId"/>
 *     &lt;enumeration value="LocationOfPresenceName"/>
 *     &lt;enumeration value="MatchType"/>
 *     &lt;enumeration value="MobilePlatform"/>
 *     &lt;enumeration value="Month"/>
 *     &lt;enumeration value="Placement"/>
 *     &lt;enumeration value="Quarter"/>
 *     &lt;enumeration value="Query"/>
 *     &lt;enumeration value="Revenue"/>
 *     &lt;enumeration value="RlAdjustmentId"/>
 *     &lt;enumeration value="Sessions"/>
 *     &lt;enumeration value="Slot"/>
 *     &lt;enumeration value="SmartBannerFilterId"/>
 *     &lt;enumeration value="TargetingLocationId"/>
 *     &lt;enumeration value="TargetingLocationName"/>
 *     &lt;enumeration value="Week"/>
 *     &lt;enumeration value="Year"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FieldEnum", namespace = "http://api.direct.yandex.com/v5/reports")
@XmlEnum
public enum FieldEnum {

    @XmlEnumValue("AdFormat")
    AD_FORMAT("AdFormat"),
    @XmlEnumValue("AdGroupId")
    AD_GROUP_ID("AdGroupId"),
    @XmlEnumValue("AdGroupName")
    AD_GROUP_NAME("AdGroupName"),
    @XmlEnumValue("AdId")
    AD_ID("AdId"),
    @XmlEnumValue("AdNetworkType")
    AD_NETWORK_TYPE("AdNetworkType"),
    @XmlEnumValue("Age")
    AGE("Age"),
    @XmlEnumValue("AudienceTargetId")
    AUDIENCE_TARGET_ID("AudienceTargetId"),
    @XmlEnumValue("AvgClickPosition")
    AVG_CLICK_POSITION("AvgClickPosition"),
    @XmlEnumValue("AvgCpc")
    AVG_CPC("AvgCpc"),
    @XmlEnumValue("AvgImpressionPosition")
    AVG_IMPRESSION_POSITION("AvgImpressionPosition"),
    @XmlEnumValue("AvgPageviews")
    AVG_PAGEVIEWS("AvgPageviews"),
    @XmlEnumValue("BounceRate")
    BOUNCE_RATE("BounceRate"),
    @XmlEnumValue("Bounces")
    BOUNCES("Bounces"),
    @XmlEnumValue("CampaignId")
    CAMPAIGN_ID("CampaignId"),
    @XmlEnumValue("CampaignName")
    CAMPAIGN_NAME("CampaignName"),
    @XmlEnumValue("CampaignType")
    CAMPAIGN_TYPE("CampaignType"),
    @XmlEnumValue("CarrierType")
    CARRIER_TYPE("CarrierType"),
    @XmlEnumValue("ClickType")
    CLICK_TYPE("ClickType"),
    @XmlEnumValue("Clicks")
    CLICKS("Clicks"),
    @XmlEnumValue("ConversionRate")
    CONVERSION_RATE("ConversionRate"),
    @XmlEnumValue("Conversions")
    CONVERSIONS("Conversions"),
    @XmlEnumValue("Cost")
    COST("Cost"),
    @XmlEnumValue("CostPerConversion")
    COST_PER_CONVERSION("CostPerConversion"),
    @XmlEnumValue("Criteria")
    CRITERIA("Criteria"),
    @XmlEnumValue("CriteriaId")
    CRITERIA_ID("CriteriaId"),
    @XmlEnumValue("CriteriaType")
    CRITERIA_TYPE("CriteriaType"),
    @XmlEnumValue("Ctr")
    CTR("Ctr"),
    @XmlEnumValue("Date")
    DATE("Date"),
    @XmlEnumValue("Device")
    DEVICE("Device"),
    @XmlEnumValue("DynamicTextAdTargetId")
    DYNAMIC_TEXT_AD_TARGET_ID("DynamicTextAdTargetId"),
    @XmlEnumValue("ExternalNetworkName")
    EXTERNAL_NETWORK_NAME("ExternalNetworkName"),
    @XmlEnumValue("Gender")
    GENDER("Gender"),
    @XmlEnumValue("GoalsRoi")
    GOALS_ROI("GoalsRoi"),
    @XmlEnumValue("ImpressionShare")
    IMPRESSION_SHARE("ImpressionShare"),
    @XmlEnumValue("Impressions")
    IMPRESSIONS("Impressions"),
    @XmlEnumValue("Keyword")
    KEYWORD("Keyword"),
    @XmlEnumValue("LocationOfPresenceId")
    LOCATION_OF_PRESENCE_ID("LocationOfPresenceId"),
    @XmlEnumValue("LocationOfPresenceName")
    LOCATION_OF_PRESENCE_NAME("LocationOfPresenceName"),
    @XmlEnumValue("MatchType")
    MATCH_TYPE("MatchType"),
    @XmlEnumValue("MobilePlatform")
    MOBILE_PLATFORM("MobilePlatform"),
    @XmlEnumValue("Month")
    MONTH("Month"),
    @XmlEnumValue("Placement")
    PLACEMENT("Placement"),
    @XmlEnumValue("Quarter")
    QUARTER("Quarter"),
    @XmlEnumValue("Query")
    QUERY("Query"),
    @XmlEnumValue("Revenue")
    REVENUE("Revenue"),
    @XmlEnumValue("RlAdjustmentId")
    RL_ADJUSTMENT_ID("RlAdjustmentId"),
    @XmlEnumValue("Sessions")
    SESSIONS("Sessions"),
    @XmlEnumValue("Slot")
    SLOT("Slot"),
    @XmlEnumValue("SmartBannerFilterId")
    SMART_BANNER_FILTER_ID("SmartBannerFilterId"),
    @XmlEnumValue("TargetingLocationId")
    TARGETING_LOCATION_ID("TargetingLocationId"),
    @XmlEnumValue("TargetingLocationName")
    TARGETING_LOCATION_NAME("TargetingLocationName"),
    @XmlEnumValue("Week")
    WEEK("Week"),
    @XmlEnumValue("Year")
    YEAR("Year");
    private final String value;

    FieldEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FieldEnum fromValue(String v) {
        for (FieldEnum c: FieldEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
