//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.21 at 11:21:27 PM SAMT 
//


package ru.cedra.metrics.domain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FilterOperatorEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FilterOperatorEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="DOES_NOT_START_WITH_ALL_IGNORE_CASE"/>
 *     &lt;enumeration value="DOES_NOT_START_WITH_IGNORE_CASE"/>
 *     &lt;enumeration value="EQUALS"/>
 *     &lt;enumeration value="GREATER_THAN"/>
 *     &lt;enumeration value="IN"/>
 *     &lt;enumeration value="LESS_THAN"/>
 *     &lt;enumeration value="NOT_EQUALS"/>
 *     &lt;enumeration value="NOT_IN"/>
 *     &lt;enumeration value="STARTS_WITH_ANY_IGNORE_CASE"/>
 *     &lt;enumeration value="STARTS_WITH_IGNORE_CASE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FilterOperatorEnum", namespace = "http://api.direct.yandex.com/v5/reports")
@XmlEnum
public enum FilterOperatorEnum {

    DOES_NOT_START_WITH_ALL_IGNORE_CASE,
    DOES_NOT_START_WITH_IGNORE_CASE,
    EQUALS,
    GREATER_THAN,
    IN,
    LESS_THAN,
    NOT_EQUALS,
    NOT_IN,
    STARTS_WITH_ANY_IGNORE_CASE,
    STARTS_WITH_IGNORE_CASE;

    public String value() {
        return name();
    }

    public static FilterOperatorEnum fromValue(String v) {
        return valueOf(v);
    }

}
