//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.21 at 11:21:27 PM SAMT 
//


package ru.cedra.metrics.domain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MobileAppAdActionEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MobileAppAdActionEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="DOWNLOAD"/>
 *     &lt;enumeration value="GET"/>
 *     &lt;enumeration value="INSTALL"/>
 *     &lt;enumeration value="MORE"/>
 *     &lt;enumeration value="OPEN"/>
 *     &lt;enumeration value="UPDATE"/>
 *     &lt;enumeration value="PLAY"/>
 *     &lt;enumeration value="BUY_AUTODETECT"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MobileAppAdActionEnum")
@XmlEnum
public enum MobileAppAdActionEnum {

    DOWNLOAD,
    GET,
    INSTALL,
    MORE,
    OPEN,
    UPDATE,
    PLAY,
    BUY_AUTODETECT;

    public String value() {
        return name();
    }

    public static MobileAppAdActionEnum fromValue(String v) {
        return valueOf(v);
    }

}
