//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.21 at 11:21:27 PM SAMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://api.direct.yandex.com/v5/general", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.cedra.metrics.domain;
