//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.21 at 11:21:27 PM SAMT 
//


package ru.cedra.metrics.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ApiError" type="{http://api.direct.yandex.com/v5/reports}ApiError"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "apiError"
})
@XmlRootElement(name = "reportDownloadError", namespace = "http://api.direct.yandex.com/v5/reports")
public class ReportDownloadError {

    @XmlElement(name = "ApiError", namespace = "http://api.direct.yandex.com/v5/reports", required = true)
    protected ApiError apiError;

    /**
     * Gets the value of the apiError property.
     * 
     * @return
     *     possible object is
     *     {@link ApiError }
     *     
     */
    public ApiError getApiError() {
        return apiError;
    }

    /**
     * Sets the value of the apiError property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApiError }
     *     
     */
    public void setApiError(ApiError value) {
        this.apiError = value;
    }

}
