//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.21 at 11:21:27 PM SAMT 
//


package ru.cedra.metrics.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Statistics complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Statistics">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Clicks" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="Impressions" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Statistics", propOrder = {
    "clicks",
    "impressions"
})
public class Statistics {

    @XmlElement(name = "Clicks", namespace = "")
    protected long clicks;
    @XmlElement(name = "Impressions", namespace = "")
    protected long impressions;

    /**
     * Gets the value of the clicks property.
     * 
     */
    public long getClicks() {
        return clicks;
    }

    /**
     * Sets the value of the clicks property.
     * 
     */
    public void setClicks(long value) {
        this.clicks = value;
    }

    /**
     * Gets the value of the impressions property.
     * 
     */
    public long getImpressions() {
        return impressions;
    }

    /**
     * Sets the value of the impressions property.
     * 
     */
    public void setImpressions(long value) {
        this.impressions = value;
    }

}
